### ISSUE TITLE
Source code for the modified Sparrow solver

### ISSUE THREAD

**Issue by jeanmonet** [zhaoyu-li/NSNet#2]
Hi, I was trying to reproduce some of your results and noticed that I couldn't find the source code for the modified `sparrow.c` that takes as argument the variable initialization file. This would be useful in order to compile the solver on different platforms. Could you please point me to where I could find it?
Many thanks

**Comment by zhaoyu-li** [comment]
Hi,

Thanks for your interest. I have uploaded the modified `sparrow.c` to this repo.

**Comment by jeanmonet** [comment]
Thank you for the prompt reply, much appreciated.
