### ISSUE TITLE
Uploading pre-trained weights

### ISSUE THREAD

**Issue by x-lad** [zhaoyu-li/NSNet#3]
Hello

Is it possible to upload they pre-trained weights?

Thanks

**Comment by zhaoyu-li** [comment]
Hi,

I apologize for my delayed response. I recently transitioned to a new school, which has unfortunately led to a loss of access to the previous cluster where our experimental data was stored. However, our experiments were conducted using three different random seeds to ensure minimal variance in the results. I am confident that you can replicate similar results with our approach. If you encounter any problems, please do not hesitate to reopen the issue and report these concerns.
